# Generated by Django 5.2.1 on 2025-10-14 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('editorial', models.CharField(max_length=200)),
                ('anio_publicacion', models.PositiveIntegerField()),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('categoria', models.CharField(max_length=100)),
                ('idioma', models.CharField(max_length=50)),
                ('numero_ejemplares', models.PositiveIntegerField(default=1)),
                ('genero', models.CharField(max_length=100)),
                ('numero_paginas', models.PositiveIntegerField()),
                ('sinopsis', models.TextField(blank=True, null=True)),
                ('serie', models.CharField(blank=True, max_length=100, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='core.autor')),
            ],
        ),
    ]
